### PR TITLE
build-medsl august 26

### LINKED ISSUE #194: [CA] Los Angeles comparison with SOV
Los Angeles (4.6m voters) shows a tiny discrepancy with the official result per MEDSL. 

For example, we have Joe Biden getting 3,028,810 votes, while Wikipedia and MEDSL have him getting 3,028,885 votes.

- [ ] Recode NO SELECTION -> UNDERVOTE (see below)

We should definitely include this county, but it would be good to document if we know why.

Note that Los Angeles has a heavily fragmented ballot and unfortuantely PRESIDENT appears cut off from the rest. However, we do get some within-legislature ticket splitting.

### PR DESCRIPTION
**Pull request by mreece13**
Changes:
- Update JSON preprocessing code to better catch undervotes, using `dominionCVR`
- Add Clark, NV #337 
- Fixes #194 
- Update all summary tables
- Rename folders per #338

### CODE REVIEW

**Comment by mreece13** [comment]
Not entirely sure why this happened, but the fix in Clark, NV for GREGORY T HAFEN II seems to have also pushed three other counties over the edge into 1% territory.

**Comment by kuriwaki** [comment]
status files look good -- but should we delete all the analysis code in `paper-analyze` since that is in progress in a different #335?

**Review by kuriwaki — APPROVED** [review]
Changes to `clean_json` and the output looks good. Only comment is to undo/delete the 05_paper-analyze directory addition, I think.

**Comment by mreece13** [comment]
Sure, I will delete it and merge

**Pull request merged**
